language: node_js

sudo: required

node_js:
  - '9'

install:
  - npm i create-elm-app -g
  - npm install -g gh-pages
  - npm i

script:
  - elm-app test
  - elm-app build

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: 'gh_pages'
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: 'build'
  on:
    branch: master